language: python
python:
  - 2.6
  - 2.7
addons:
  apt:
    packages:
      - tcl8.5
install:
    # install easybuild-framework (and dependencies)
    # use framework 'develop' branch, except when testing 'master'
    - if [ "x$TRAVIS_BRANCH" = 'xmaster' ]; then BRANCH=master; else BRANCH=develop; fi
    - curl -si https://api.github.com/repos/hpcugent/easybuild-framework/git/refs/heads/${BRANCH} | grep sha
    - easy_install https://github.com/hpcugent/easybuild-framework/archive/${BRANCH}.tar.gz
script:
    - export PYTHONPATH=$TRAVIS_BUILD_DIR
    - python -O -m test.easyblocks.suite
