language: python
python: 2.6
env:
  matrix:
    - ENV_MOD_VERSION=3.2.10 EASYBUILD_MODULES_TOOL=EnvironmentModulesC EASYBUILD_MODULE_SYNTAX=Tcl
    - LMOD_VERSION=6.6.3
    - LMOD_VERSION=6.6.3 EASYBUILD_MODULE_SYNTAX=Tcl
    - LMOD_VERSION=7.8.5
    - LMOD_VERSION=7.8.5 EASYBUILD_MODULE_SYNTAX=Tcl
    # Tmod 4.1.4 is used in RHEL8
    - ENV_MOD_VERSION=4.1.4 EASYBUILD_MODULES_TOOL=EnvironmentModules EASYBUILD_MODULE_SYNTAX=Tcl
matrix:
  # mark build as finished as soon as job has failed
  fast_finish: true
  include:
    # also test default configuration with Python 2.7
    - python: 2.7
      env: LMOD_VERSION=7.8.5
    # also test with Python 3.6
    - python: 3.6
      env: LMOD_VERSION=6.6.3
    - python: 3.6
      env: LMOD_VERSION=6.5.1 TEST_EASYBUILD_MODULE_SYNTAX=Tcl
    - python: 3.6
      env: LMOD_VERSION=7.8.5
    - python: 3.6
      env: LMOD_VERSION=7.8.5 TEST_EASYBUILD_MODULE_SYNTAX=Tcl
    - python: 3.6
      env: ENV_MOD_VERSION=3.2.10 TEST_EASYBUILD_MODULES_TOOL=EnvironmentModulesC TEST_EASYBUILD_MODULE_SYNTAX=Tcl
    - python: 3.6
      env: ENV_MOD_VERSION=4.1.4 TEST_EASYBUILD_MODULE_SYNTAX=Tcl TEST_EASYBUILD_MODULES_TOOL=EnvironmentModules
addons:
  apt:
    packages:
      - tcl8.5
      # for testing OpenMPI-system*eb we need to have Open MPI installed
      - libopenmpi-dev
      - openmpi-bin
install:
    # install easybuild-framework (and dependencies)
    # prefer clone & easy_install over easy_install directly in order to obtain information of what was installed exactly
    # use framework 'develop' branch, except when testing 'master'
    - if [ "x$TRAVIS_BRANCH" = 'xmaster' ]; then BRANCH=master; else BRANCH=develop; fi
    - if [ "x$TRAVIS_BRANCH" = 'x4.x' ]; then BRANCH=4.x; else BRANCH=develop; fi
    - echo "Using easybuild-framework branch $BRANCH (\$TRAVIS_BRANCH: $TRAVIS_BRANCH)"
    - git clone -b $BRANCH --depth 10 --single-branch https://github.com/easybuilders/easybuild-framework.git
    - cd easybuild-framework; git log -n 1; cd -
    - easy_install $PWD/easybuild-framework
    # install environment modules tool using 'install_eb_dep.sh' script provided by easybuild-framework
    - if [ ! -z $ENV_MOD_VERSION ]; then source $(which install_eb_dep.sh) modules-${ENV_MOD_VERSION} $HOME; fi
    - if [ ! -z $LMOD_VERSION ]; then source $(which install_eb_dep.sh) lua-5.1.4.8 $HOME; fi
    - if [ ! -z $LMOD_VERSION ]; then source $(which install_eb_dep.sh) Lmod-${LMOD_VERSION} $HOME; fi
script:
    # make sure 'ml' alias is defined, otherwise sourcing the init script fails (silently) for Lmod (< 5.9.3)
    - if [ ! -z $MOD_INIT ] && [ ! -z $LMOD_VERSION ]; then alias ml=foobar; fi
    # set up environment for modules tool (if $MOD_INIT is defined)
    - if [ ! -z $MOD_INIT ]; then source $MOD_INIT; type module; fi
    - export PYTHONPATH=$TRAVIS_BUILD_DIR
    - python -O -m test.easyblocks.suite
